vich_uploader:
    db_driver: orm

    mappings:
        image_upload:
            uri_prefix: '%image_upload%'
            upload_destination: '%kernel.project_dir%/public%image_upload%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
